### ISSUE TITLE
Training time, mixed precision and inference time.

### ISSUE THREAD

**Issue by DavidePaglieri** [google-research/frame-interpolation#14]
Hello!

Can I ask you what is the full training time of the model with 8 V100 GPUs? Also, have you tried mixed precision training? If so, what is the performance both in terms of efficiency and final PSNR? 

Another question I have is the following, when you do recursive interpolation to achieve 4x, 8x, 16x slow motion and so on, wouldn't it be faster if the feature extraction was done only once per image pair, and only the flow estimator and fusion networks were used recursively?

Thank you!

**Comment by fitsumreda** [comment]
Training with Style loss takes about 5 days, and with L1 alone about 4.5 days on 8 V100s. If you use more than 8, say 40 V100 GPUs, it can train in 1.5 days, and you can get comparable results (slightly lower quantitatively, but no noticeable qualitative differences). You will need to set `strategy = tf.distribute.MultiWorkerMirroredStrategy()` instead of `strategy = tf.distribute.MirroredStrategy()' for mulit-node distributed training.

No, I didn't try mixed-precision, great idea to further speed up training, though!

To you last question: It'd be faster, but the results were inferior. The current recursive approach has the advantage of creating piece-wise linear (i.e. non-linear) movements when compared to simply time-modulating the once extracted features or bi-directional flows.

**Comment by DavidePaglieri** [comment]
I see, thank you for pointing that out! 

So if you used the same network and calculated the bidirectional optical flow at different scales like you do, then forward warped the feature maps (similar to softmax splatting) at the desired time, and finally applied the U-Net for refinement, the final result would be lower quality because you would be approximating linear motion only right?

This to me is a bit confusing, because intuitively I would think that given two frames, if you interpolate the one in between, it will be temporally and spacially equally spaced in between the inputs. So if you kept doing that recursively to get further frames, they will also be equally spaced in between the recursed input frames, so I am not sure how that would make it non-linear...

**Comment by fitsumreda** [comment]
I'll close this issue since it's not related to the codes. Happy to answer questions or clarify confusions. Feel free to contact me via the email (available in README).
